# Generated by Django 4.0.2 on 2022-03-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Crossover', 'Crossover'), ('Hatchback', 'Hatchback')], max_length=100),
        ),
    ]
