version: '3.8'

services:
  web:
    build: ./car_showroom
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./car_showroom/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./car_showroom/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./car_showroom/.env.dev




