version: '3.8'

services:
  web:
    build: ./car_showroom
    volumes:
      - ./car_showroom/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./car_showroom/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./car_showroom/.env.dev

  redis:
    image: redis:alpine

  celery:
      build: ./car_showroom
      command: celery -A config worker -l info
      volumes:
        - ./car_showroom/:/usr/src/app/
      env_file:
        - ./car_showroom/.env.dev
      depends_on:
        - db
        - redis
        - web

  celery-beat:
      build: ./car_showroom
      command: celery -A config beat -l info
      volumes:
        - ./car_showroom/:/usr/src/app/
      env_file:
        - ./car_showroom/.env.dev
      depends_on:
        - redis



