# Generated by Django 4.0.2 on 2022-02-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='is_active',
        ),
    ]
