# Generated by Django 4.0.2 on 2022-02-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('foundation_year', models.DateField()),
                ('cars', models.ManyToManyField(blank=True, null=True, to='car.Car')),
                ('showrooms', models.ManyToManyField(blank=True, null=True, to='showroom.Showroom')),
            ],
            options={
                'abstract': False,
            },
        ),

        migrations.CreateModel(
            name='SupplierDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cars', models.ManyToManyField(to='car.Car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
